name: universal_datastores
description: A powerful, reusable, and easy-to-manage Dart package for creating and using local database mock data, speeding up UI development and improving testability.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

