name: universal_datastores
description: A powerful, reusable, and easy-to-manage Dart package for creating and using local database mock data, speeding up UI development and improving testability.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
